"""Add timestamps to departments table

Revision ID: 30129732020c
Revises: 5193c0303071
Create Date: 2025-07-16 19:05:38.639054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30129732020c'
down_revision: Union[str, Sequence[str], None] = '5193c0303071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departmentsTable', sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('departmentsTable', sa.Column('dateUpdated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departmentsTable', 'dateUpdated')
    op.drop_column('departmentsTable', 'dateCreated')
    # ### end Alembic commands ###
