"""Add timing fields for scripts

Revision ID: 351e0a0a1525
Revises: be4fa3492eac
Create Date: 2025-07-04 11:17:16.942503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351e0a0a1525'
down_revision: Union[str, Sequence[str], None] = 'be4fa3492eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scriptElementsTable', sa.Column('timeOffset', sa.Interval(), nullable=False))
    op.add_column('scriptsTable', sa.Column('intendedStartTime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scriptsTable', sa.Column('actualStartTime', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scriptsTable', 'actualStartTime')
    op.drop_column('scriptsTable', 'intendedStartTime')
    op.drop_column('scriptElementsTable', 'timeOffset')
    # ### end Alembic commands ###
