"""Add comprehensive venue fields

Revision ID: 5193c0303071
Revises: 45f26642dfd5
Create Date: 2025-07-16 17:41:25.281066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5193c0303071'
down_revision: Union[str, Sequence[str], None] = '45f26642dfd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venuesTable', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('venuesTable', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('venuesTable', sa.Column('venueType', sa.String(), nullable=True))
    op.add_column('venuesTable', sa.Column('contactName', sa.String(), nullable=True))
    op.add_column('venuesTable', sa.Column('contactEmail', sa.String(), nullable=True))
    op.add_column('venuesTable', sa.Column('contactPhone', sa.String(), nullable=True))
    op.add_column('venuesTable', sa.Column('stageWidth', sa.Integer(), nullable=True))
    op.add_column('venuesTable', sa.Column('stageDepth', sa.Integer(), nullable=True))
    op.add_column('venuesTable', sa.Column('flyHeight', sa.Integer(), nullable=True))
    op.add_column('venuesTable', sa.Column('equipment', sa.JSON(), nullable=True))
    op.add_column('venuesTable', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('venuesTable', sa.Column('rentalRate', sa.Integer(), nullable=True))
    op.add_column('venuesTable', sa.Column('minimumRental', sa.Integer(), nullable=True))
    op.add_column('venuesTable', sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('venuesTable', sa.Column('dateUpdated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venuesTable', 'dateUpdated')
    op.drop_column('venuesTable', 'dateCreated')
    op.drop_column('venuesTable', 'minimumRental')
    op.drop_column('venuesTable', 'rentalRate')
    op.drop_column('venuesTable', 'notes')
    op.drop_column('venuesTable', 'equipment')
    op.drop_column('venuesTable', 'flyHeight')
    op.drop_column('venuesTable', 'stageDepth')
    op.drop_column('venuesTable', 'stageWidth')
    op.drop_column('venuesTable', 'contactPhone')
    op.drop_column('venuesTable', 'contactEmail')
    op.drop_column('venuesTable', 'contactName')
    op.drop_column('venuesTable', 'venueType')
    op.drop_column('venuesTable', 'capacity')
    op.drop_column('venuesTable', 'address')
    # ### end Alembic commands ###
