"""Move sharing functionality from script_shares to crew_assignments

Revision ID: 640cf4f85a4a
Revises: 20250814_212000
Create Date: 2025-08-15 05:56:42.930513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '640cf4f85a4a'
down_revision: Union[str, Sequence[str], None] = '20250814_212000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_script_shares_script_id'), table_name='script_shares')
    op.drop_index(op.f('ix_script_shares_share_id'), table_name='script_shares')
    op.drop_index(op.f('ix_script_shares_share_token'), table_name='script_shares')
    op.drop_index(op.f('ix_script_shares_shared_with_user_id'), table_name='script_shares')
    op.drop_table('script_shares')
    op.add_column('crewAssignmentsTable', sa.Column('share_token', sa.String(length=255), nullable=True))
    op.add_column('crewAssignmentsTable', sa.Column('access_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('crewAssignmentsTable', sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_crewAssignmentsTable_share_token'), 'crewAssignmentsTable', ['share_token'], unique=True)
    op.drop_constraint(op.f('scriptElementsTable_parent_element_id_fkey'), 'scriptElementsTable', type_='foreignkey')
    op.create_foreign_key(None, 'scriptElementsTable', 'scriptElementsTable', ['parent_element_id'], ['element_id'])
    op.alter_column('userTable', 'user_role',
               existing_type=postgresql.ENUM('CREW', 'ASSISTANT_DIRECTOR', 'STAGE_MANAGER', 'ASSISTANT_STAGE_MANAGER', 'TECHNICAL_DIRECTOR', 'LIGHTING_DESIGNER', 'SOUND_DESIGNER', 'PROPS_MASTER', 'ELECTRICIAN', 'SOUND_TECHNICIAN', 'PROJECTIONIST', 'RECORDIST', 'LEAD_AUDIO', 'LEAD_VIDEO', 'GRAPHICS', 'FLY_OPERATOR', 'CARPENTER', 'PRODUCER', 'DIRECTOR', 'OTHER', name='user_role_enum'),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('userTable_created_by_fkey'), 'userTable', type_='foreignkey')
    op.create_foreign_key(None, 'userTable', 'userTable', ['created_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userTable', type_='foreignkey')
    op.create_foreign_key(op.f('userTable_created_by_fkey'), 'userTable', 'userTable', ['created_by'], ['user_id'], initially='DEFERRED', deferrable=True)
    op.alter_column('userTable', 'user_role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CREW', 'ASSISTANT_DIRECTOR', 'STAGE_MANAGER', 'ASSISTANT_STAGE_MANAGER', 'TECHNICAL_DIRECTOR', 'LIGHTING_DESIGNER', 'SOUND_DESIGNER', 'PROPS_MASTER', 'ELECTRICIAN', 'SOUND_TECHNICIAN', 'PROJECTIONIST', 'RECORDIST', 'LEAD_AUDIO', 'LEAD_VIDEO', 'GRAPHICS', 'FLY_OPERATOR', 'CARPENTER', 'PRODUCER', 'DIRECTOR', 'OTHER', name='user_role_enum'),
               existing_nullable=True)
    op.drop_constraint(None, 'scriptElementsTable', type_='foreignkey')
    op.create_foreign_key(op.f('scriptElementsTable_parent_element_id_fkey'), 'scriptElementsTable', 'scriptElementsTable', ['parent_element_id'], ['element_id'], initially='DEFERRED', deferrable=True)
    op.drop_index(op.f('ix_crewAssignmentsTable_share_token'), table_name='crewAssignmentsTable')
    op.drop_column('crewAssignmentsTable', 'last_accessed_at')
    op.drop_column('crewAssignmentsTable', 'access_count')
    op.drop_column('crewAssignmentsTable', 'share_token')
    op.create_table('script_shares',
    sa.Column('share_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('script_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shared_with_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('share_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('access_count', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'),
    sa.Column('last_accessed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_accessed_by_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('share_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['userTable.user_id'], name=op.f('script_shares_created_by_fkey')),
    sa.ForeignKeyConstraint(['script_id'], ['scriptsTable.script_id'], name=op.f('script_shares_script_id_fkey')),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['userTable.user_id'], name=op.f('script_shares_shared_with_user_id_fkey')),
    sa.PrimaryKeyConstraint('share_id', name=op.f('script_shares_pkey'))
    )
    op.create_index(op.f('ix_script_shares_shared_with_user_id'), 'script_shares', ['shared_with_user_id'], unique=False)
    op.create_index(op.f('ix_script_shares_share_token'), 'script_shares', ['share_token'], unique=True)
    op.create_index(op.f('ix_script_shares_share_id'), 'script_shares', ['share_id'], unique=False)
    op.create_index(op.f('ix_script_shares_script_id'), 'script_shares', ['script_id'], unique=False)
    # ### end Alembic commands ###
