"""Add unified user model with guest user support

Revision ID: 7d3f70ac8e95
Revises: 30129732020c
Create Date: 2025-07-17 01:47:29.889511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3f70ac8e95'
down_revision: Union[str, Sequence[str], None] = '30129732020c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crewAssignmentsTable', sa.Column('assignmentID', sa.Integer(), nullable=False))
    op.add_column('crewAssignmentsTable', sa.Column('showRole', sa.String(), nullable=True))
    op.add_column('crewAssignmentsTable', sa.Column('isActive', sa.Boolean(), nullable=False))
    op.add_column('crewAssignmentsTable', sa.Column('dateAssigned', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('crewAssignmentsTable', 'showID',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('crewAssignmentsTable_showID_userID_departmentID_key'), 'crewAssignmentsTable', type_='unique')
    op.create_index(op.f('ix_crewAssignmentsTable_assignmentID'), 'crewAssignmentsTable', ['assignmentID'], unique=False)
    op.create_unique_constraint('unique_user_show_dept', 'crewAssignmentsTable', ['showID', 'userID', 'departmentID'])
    op.add_column('userTable', sa.Column('phoneNumber', sa.String(), nullable=True))
    op.add_column('userTable', sa.Column('userStatus', sa.Enum('GUEST', 'VERIFIED', 'INVITED', 'INACTIVE', name='userstatus'), nullable=False))
    op.add_column('userTable', sa.Column('createdBy', sa.Integer(), nullable=True))
    op.add_column('userTable', sa.Column('invitedAt', sa.DateTime(), nullable=True))
    op.add_column('userTable', sa.Column('invitationToken', sa.String(), nullable=True))
    op.add_column('userTable', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('userTable', 'clerk_user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('userTable', 'emailAddress',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('userTable', 'fullnameFirst',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('userTable', 'fullnameLast',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'userTable', ['invitationToken'])
    op.create_foreign_key(None, 'userTable', 'userTable', ['createdBy'], ['ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userTable', type_='foreignkey')
    op.drop_constraint(None, 'userTable', type_='unique')
    op.alter_column('userTable', 'fullnameLast',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('userTable', 'fullnameFirst',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('userTable', 'emailAddress',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('userTable', 'clerk_user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('userTable', 'notes')
    op.drop_column('userTable', 'invitationToken')
    op.drop_column('userTable', 'invitedAt')
    op.drop_column('userTable', 'createdBy')
    op.drop_column('userTable', 'userStatus')
    op.drop_column('userTable', 'phoneNumber')
    op.drop_constraint('unique_user_show_dept', 'crewAssignmentsTable', type_='unique')
    op.drop_index(op.f('ix_crewAssignmentsTable_assignmentID'), table_name='crewAssignmentsTable')
    op.create_unique_constraint(op.f('crewAssignmentsTable_showID_userID_departmentID_key'), 'crewAssignmentsTable', ['showID', 'userID', 'departmentID'], postgresql_nulls_not_distinct=False)
    op.alter_column('crewAssignmentsTable', 'showID',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('crewAssignmentsTable', 'dateAssigned')
    op.drop_column('crewAssignmentsTable', 'isActive')
    op.drop_column('crewAssignmentsTable', 'showRole')
    op.drop_column('crewAssignmentsTable', 'assignmentID')
    # ### end Alembic commands ###
