"""Initial migration with unified user model

Revision ID: 8b8af524dabc
Revises: 7d3f70ac8e95
Create Date: 2025-07-17 01:55:09.022026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8af524dabc'
down_revision: Union[str, Sequence[str], None] = '7d3f70ac8e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userTable',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=True),
    sa.Column('emailAddress', sa.String(), nullable=False),
    sa.Column('fullnameFirst', sa.String(), nullable=False),
    sa.Column('fullnameLast', sa.String(), nullable=False),
    sa.Column('userName', sa.String(), nullable=True),
    sa.Column('profileImgURL', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('userStatus', sa.Enum('GUEST', 'VERIFIED', 'INVITED', 'INACTIVE', name='userstatus'), nullable=False),
    sa.Column('userRole', sa.String(), nullable=True),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('invitedAt', sa.DateTime(), nullable=True),
    sa.Column('invitationToken', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dateUpdated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['userTable.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('invitationToken')
    )
    op.create_index(op.f('ix_userTable_ID'), 'userTable', ['ID'], unique=False)
    op.create_index(op.f('ix_userTable_clerk_user_id'), 'userTable', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_userTable_emailAddress'), 'userTable', ['emailAddress'], unique=True)
    op.create_index(op.f('ix_userTable_userName'), 'userTable', ['userName'], unique=True)
    op.add_column('crewAssignmentsTable', sa.Column('assignmentID', sa.Integer(), nullable=False))
    op.add_column('crewAssignmentsTable', sa.Column('showRole', sa.String(), nullable=True))
    op.add_column('crewAssignmentsTable', sa.Column('isActive', sa.Boolean(), nullable=False))
    op.add_column('crewAssignmentsTable', sa.Column('dateAssigned', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('crewAssignmentsTable', 'showID',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('crewAssignmentsTable_showID_userID_departmentID_key'), 'crewAssignmentsTable', type_='unique')
    op.create_index(op.f('ix_crewAssignmentsTable_assignmentID'), 'crewAssignmentsTable', ['assignmentID'], unique=False)
    op.create_unique_constraint('unique_user_show_dept', 'crewAssignmentsTable', ['showID', 'userID', 'departmentID'])
    op.create_foreign_key(None, 'crewAssignmentsTable', 'userTable', ['userID'], ['ID'])
    op.add_column('departmentsTable', sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('departmentsTable', sa.Column('dateUpdated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'showsTable', 'userTable', ['ownerID'], ['ID'])
    op.add_column('venuesTable', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('venuesTable', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('venuesTable', sa.Column('venueType', sa.String(), nullable=True))
    op.add_column('venuesTable', sa.Column('contactName', sa.String(), nullable=True))
    op.add_column('venuesTable', sa.Column('contactEmail', sa.String(), nullable=True))
    op.add_column('venuesTable', sa.Column('contactPhone', sa.String(), nullable=True))
    op.add_column('venuesTable', sa.Column('stageWidth', sa.Integer(), nullable=True))
    op.add_column('venuesTable', sa.Column('stageDepth', sa.Integer(), nullable=True))
    op.add_column('venuesTable', sa.Column('flyHeight', sa.Integer(), nullable=True))
    op.add_column('venuesTable', sa.Column('equipment', sa.JSON(), nullable=True))
    op.add_column('venuesTable', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('venuesTable', sa.Column('rentalRate', sa.Integer(), nullable=True))
    op.add_column('venuesTable', sa.Column('minimumRental', sa.Integer(), nullable=True))
    op.add_column('venuesTable', sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('venuesTable', sa.Column('dateUpdated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venuesTable', 'dateUpdated')
    op.drop_column('venuesTable', 'dateCreated')
    op.drop_column('venuesTable', 'minimumRental')
    op.drop_column('venuesTable', 'rentalRate')
    op.drop_column('venuesTable', 'notes')
    op.drop_column('venuesTable', 'equipment')
    op.drop_column('venuesTable', 'flyHeight')
    op.drop_column('venuesTable', 'stageDepth')
    op.drop_column('venuesTable', 'stageWidth')
    op.drop_column('venuesTable', 'contactPhone')
    op.drop_column('venuesTable', 'contactEmail')
    op.drop_column('venuesTable', 'contactName')
    op.drop_column('venuesTable', 'venueType')
    op.drop_column('venuesTable', 'capacity')
    op.drop_column('venuesTable', 'address')
    op.drop_constraint(None, 'showsTable', type_='foreignkey')
    op.drop_column('departmentsTable', 'dateUpdated')
    op.drop_column('departmentsTable', 'dateCreated')
    op.drop_constraint(None, 'crewAssignmentsTable', type_='foreignkey')
    op.drop_constraint('unique_user_show_dept', 'crewAssignmentsTable', type_='unique')
    op.drop_index(op.f('ix_crewAssignmentsTable_assignmentID'), table_name='crewAssignmentsTable')
    op.create_unique_constraint(op.f('crewAssignmentsTable_showID_userID_departmentID_key'), 'crewAssignmentsTable', ['showID', 'userID', 'departmentID'], postgresql_nulls_not_distinct=False)
    op.alter_column('crewAssignmentsTable', 'showID',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('crewAssignmentsTable', 'dateAssigned')
    op.drop_column('crewAssignmentsTable', 'isActive')
    op.drop_column('crewAssignmentsTable', 'showRole')
    op.drop_column('crewAssignmentsTable', 'assignmentID')
    op.drop_index(op.f('ix_userTable_userName'), table_name='userTable')
    op.drop_index(op.f('ix_userTable_emailAddress'), table_name='userTable')
    op.drop_index(op.f('ix_userTable_clerk_user_id'), table_name='userTable')
    op.drop_index(op.f('ix_userTable_ID'), table_name='userTable')
    op.drop_table('userTable')
    # ### end Alembic commands ###
