# backend/alembic/versions/a2471fd11a8a_initial_migration.py

"""initial_migration

Revision ID: a2471fd11a8a
Revises: 
Create Date: 2025-07-18 01:43:11.466287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2471fd11a8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departmentsTable',
    sa.Column('departmentID', sa.UUID(), nullable=False),
    sa.Column('departmentName', sa.String(), nullable=False),
    sa.Column('departmentDescription', sa.String(), nullable=True),
    sa.Column('departmentColor', sa.String(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dateUpdated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('departmentID')
    )
    op.create_index(op.f('ix_departmentsTable_departmentID'), 'departmentsTable', ['departmentID'], unique=False)
    op.create_table('userTable',
    sa.Column('userID', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=True),
    sa.Column('emailAddress', sa.String(), nullable=False),
    sa.Column('fullnameFirst', sa.String(), nullable=False),
    sa.Column('fullnameLast', sa.String(), nullable=False),
    sa.Column('userName', sa.String(), nullable=True),
    sa.Column('profileImgURL', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('userStatus', sa.Enum('GUEST', 'VERIFIED', name='userstatus'), nullable=False),
    sa.Column('userRole', sa.String(), nullable=True),
    sa.Column('createdBy', sa.UUID(), nullable=True),
    sa.Column('invitedAt', sa.DateTime(), nullable=True),
    sa.Column('invitationToken', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dateUpdated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['userTable.userID'], ),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('invitationToken')
    )
    op.create_index(op.f('ix_userTable_clerk_user_id'), 'userTable', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_userTable_emailAddress'), 'userTable', ['emailAddress'], unique=True)
    op.create_index(op.f('ix_userTable_userID'), 'userTable', ['userID'], unique=False)
    op.create_index(op.f('ix_userTable_userName'), 'userTable', ['userName'], unique=True)
    op.create_table('venuesTable',
    sa.Column('venueID', sa.UUID(), nullable=False),
    sa.Column('venueName', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('venueType', sa.String(), nullable=True),
    sa.Column('contactName', sa.String(), nullable=True),
    sa.Column('contactEmail', sa.String(), nullable=True),
    sa.Column('contactPhone', sa.String(), nullable=True),
    sa.Column('stageWidth', sa.Integer(), nullable=True),
    sa.Column('stageDepth', sa.Integer(), nullable=True),
    sa.Column('flyHeight', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rentalRate', sa.Integer(), nullable=True),
    sa.Column('minimumRental', sa.Integer(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dateUpdated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('venueID'),
    sa.UniqueConstraint('venueName')
    )
    op.create_index(op.f('ix_venuesTable_venueID'), 'venuesTable', ['venueID'], unique=False)
    op.create_table('crewRelationshipsTable',
    sa.Column('relationshipID', sa.UUID(), nullable=False),
    sa.Column('manager_user_id', sa.UUID(), nullable=False),
    sa.Column('crew_user_id', sa.UUID(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dateUpdated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crew_user_id'], ['userTable.userID'], ),
    sa.ForeignKeyConstraint(['manager_user_id'], ['userTable.userID'], ),
    sa.PrimaryKeyConstraint('relationshipID'),
    sa.UniqueConstraint('manager_user_id', 'crew_user_id', name='unique_manager_crew')
    )
    op.create_index(op.f('ix_crewRelationshipsTable_relationshipID'), 'crewRelationshipsTable', ['relationshipID'], unique=False)
    op.create_table('showsTable',
    sa.Column('showID', sa.UUID(), nullable=False),
    sa.Column('showName', sa.String(), nullable=False),
    sa.Column('showDate', sa.Date(), nullable=True),
    sa.Column('showNotes', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('venueID', sa.UUID(), nullable=True),
    sa.Column('ownerID', sa.UUID(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dateUpdated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ownerID'], ['userTable.userID'], ),
    sa.ForeignKeyConstraint(['venueID'], ['venuesTable.venueID'], ),
    sa.PrimaryKeyConstraint('showID')
    )
    op.create_index(op.f('ix_showsTable_showName'), 'showsTable', ['showName'], unique=False)
    op.create_table('crewAssignmentsTable',
    sa.Column('assignmentID', sa.UUID(), nullable=False),
    sa.Column('showID', sa.UUID(), nullable=False),
    sa.Column('userID', sa.UUID(), nullable=False),
    sa.Column('departmentID', sa.UUID(), nullable=False),
    sa.Column('showRole', sa.String(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('dateAssigned', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['departmentID'], ['departmentsTable.departmentID'], ),
    sa.ForeignKeyConstraint(['showID'], ['showsTable.showID'], ),
    sa.ForeignKeyConstraint(['userID'], ['userTable.userID'], ),
    sa.PrimaryKeyConstraint('assignmentID'),
    sa.UniqueConstraint('showID', 'userID', 'departmentID', name='unique_user_show_dept')
    )
    op.create_index(op.f('ix_crewAssignmentsTable_assignmentID'), 'crewAssignmentsTable', ['assignmentID'], unique=False)
    op.create_table('guestAccessLinksTable',
    sa.Column('linkID', sa.UUID(), nullable=False),
    sa.Column('accessToken', sa.String(), nullable=False),
    sa.Column('showID', sa.UUID(), nullable=False),
    sa.Column('departmentID', sa.UUID(), nullable=False),
    sa.Column('linkName', sa.String(), nullable=True),
    sa.Column('expiresAt', sa.DateTime(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['departmentID'], ['departmentsTable.departmentID'], ),
    sa.ForeignKeyConstraint(['showID'], ['showsTable.showID'], ),
    sa.PrimaryKeyConstraint('linkID')
    )
    op.create_index(op.f('ix_guestAccessLinksTable_accessToken'), 'guestAccessLinksTable', ['accessToken'], unique=True)
    op.create_index(op.f('ix_guestAccessLinksTable_linkID'), 'guestAccessLinksTable', ['linkID'], unique=False)
    op.create_table('scriptsTable',
    sa.Column('scriptID', sa.UUID(), nullable=False),
    sa.Column('scriptName', sa.String(), nullable=False),
    sa.Column('scriptStatus', sa.String(), nullable=True),
    sa.Column('intendedStartTime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actualStartTime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('isPinned', sa.Boolean(), nullable=False),
    sa.Column('showID', sa.UUID(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dateUpdated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['showID'], ['showsTable.showID'], ),
    sa.PrimaryKeyConstraint('scriptID')
    )
    op.create_table('scriptElementsTable',
    sa.Column('elementID', sa.UUID(), nullable=False),
    sa.Column('scriptID', sa.UUID(), nullable=False),
    sa.Column('departmentID', sa.UUID(), nullable=False),
    sa.Column('elementType', sa.Enum('CUE', 'NOTE', 'MARKER', 'STANDBY', 'WARNING', name='elementtype'), nullable=False),
    sa.Column('elementOrder', sa.Integer(), nullable=False),
    sa.Column('cueNumber', sa.String(), nullable=True),
    sa.Column('elementDescription', sa.Text(), nullable=True),
    sa.Column('timeOffset', sa.Interval(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['departmentID'], ['departmentsTable.departmentID'], ),
    sa.ForeignKeyConstraint(['scriptID'], ['scriptsTable.scriptID'], ),
    sa.PrimaryKeyConstraint('elementID')
    )
    op.create_index('idx_scriptelement_script_order', 'scriptElementsTable', ['scriptID', 'elementOrder'], unique=False)
    op.create_index('idx_scriptelement_timeoffset', 'scriptElementsTable', ['timeOffset'], unique=False)
    op.create_index(op.f('ix_scriptElementsTable_elementID'), 'scriptElementsTable', ['elementID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scriptElementsTable_elementID'), table_name='scriptElementsTable')
    op.drop_index('idx_scriptelement_timeoffset', table_name='scriptElementsTable')
    op.drop_index('idx_scriptelement_script_order', table_name='scriptElementsTable')
    op.drop_table('scriptElementsTable')
    op.drop_table('scriptsTable')
    op.drop_index(op.f('ix_guestAccessLinksTable_linkID'), table_name='guestAccessLinksTable')
    op.drop_index(op.f('ix_guestAccessLinksTable_accessToken'), table_name='guestAccessLinksTable')
    op.drop_table('guestAccessLinksTable')
    op.drop_index(op.f('ix_crewAssignmentsTable_assignmentID'), table_name='crewAssignmentsTable')
    op.drop_table('crewAssignmentsTable')
    op.drop_index(op.f('ix_showsTable_showName'), table_name='showsTable')
    op.drop_table('showsTable')
    op.drop_index(op.f('ix_crewRelationshipsTable_relationshipID'), table_name='crewRelationshipsTable')
    op.drop_table('crewRelationshipsTable')
    op.drop_index(op.f('ix_venuesTable_venueID'), table_name='venuesTable')
    op.drop_table('venuesTable')
    op.drop_index(op.f('ix_userTable_userName'), table_name='userTable')
    op.drop_index(op.f('ix_userTable_userID'), table_name='userTable')
    op.drop_index(op.f('ix_userTable_emailAddress'), table_name='userTable')
    op.drop_index(op.f('ix_userTable_clerk_user_id'), table_name='userTable')
    op.drop_table('userTable')
    op.drop_index(op.f('ix_departmentsTable_departmentID'), table_name='departmentsTable')
    op.drop_table('departmentsTable')
    # ### end Alembic commands ###
