"""Add timestamps to scripts table

Revision ID: b0060eed98f3
Revises: a7697b0d1b10
Create Date: 2025-07-07 23:44:03.004519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0060eed98f3'
down_revision: Union[str, Sequence[str], None] = 'a7697b0d1b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scriptsTable', sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('scriptsTable', sa.Column('dateUpdated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('scriptsTable', 'scriptName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scriptsTable', 'scriptName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('scriptsTable', 'dateUpdated')
    op.drop_column('scriptsTable', 'dateCreated')
    # ### end Alembic commands ###
