"""Recreate scriptElements table with correct interval type

Revision ID: baa5434a269d
Revises: 351e0a0a1525
Create Date: 2025-07-04 11:26:53.125856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa5434a269d'
down_revision: Union[str, Sequence[str], None] = '351e0a0a1525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scriptElementsTable',
    sa.Column('elementID', sa.Integer(), nullable=False),
    sa.Column('scriptID', sa.Integer(), nullable=True),
    sa.Column('departmentID', sa.Integer(), nullable=True),
    sa.Column('elementType', sa.String(), nullable=True),
    sa.Column('elementOrder', sa.Integer(), nullable=False),
    sa.Column('cueNumber', sa.String(), nullable=True),
    sa.Column('elementDescription', sa.Text(), nullable=True),
    sa.Column('timeOffset', sa.Interval(), nullable=False),
    sa.ForeignKeyConstraint(['departmentID'], ['departmentsTable.departmentID'], ),
    sa.ForeignKeyConstraint(['scriptID'], ['scriptsTable.scriptID'], ),
    sa.PrimaryKeyConstraint('elementID')
    )
    op.create_index(op.f('ix_scriptElementsTable_elementID'), 'scriptElementsTable', ['elementID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scriptElementsTable_elementID'), table_name='scriptElementsTable')
    op.drop_table('scriptElementsTable')
    # ### end Alembic commands ###
