"""Create initial tables with UUIDs

Revision ID: be4fa3492eac
Revises: 62833b123460
Create Date: 2025-07-04 10:26:17.757187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be4fa3492eac'
down_revision: Union[str, Sequence[str], None] = '62833b123460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departmentsTable',
    sa.Column('departmentID', sa.Integer(), nullable=False),
    sa.Column('departmentName', sa.String(), nullable=False),
    sa.Column('departmentDescription', sa.String(), nullable=True),
    sa.Column('departmentColor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('departmentID')
    )
    op.create_index(op.f('ix_departmentsTable_departmentID'), 'departmentsTable', ['departmentID'], unique=False)
    op.create_table('userTable',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('userName', sa.String(), nullable=True),
    sa.Column('emailAddress', sa.String(), nullable=True),
    sa.Column('fullnameFirst', sa.String(), nullable=True),
    sa.Column('fullnameLast', sa.String(), nullable=True),
    sa.Column('profileImgURL', sa.String(), nullable=True),
    sa.Column('userRole', sa.String(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dateUpdated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_userTable_ID'), 'userTable', ['ID'], unique=False)
    op.create_index(op.f('ix_userTable_clerk_user_id'), 'userTable', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_userTable_emailAddress'), 'userTable', ['emailAddress'], unique=True)
    op.create_index(op.f('ix_userTable_userName'), 'userTable', ['userName'], unique=True)
    op.create_table('showsTable',
    sa.Column('showID', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('showName', sa.String(), nullable=False),
    sa.Column('showVenue', sa.String(), nullable=True),
    sa.Column('showDate', sa.Date(), nullable=True),
    sa.Column('ownerID', sa.Integer(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dateUpdated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ownerID'], ['userTable.ID'], ),
    sa.PrimaryKeyConstraint('showID')
    )
    op.create_index(op.f('ix_showsTable_showName'), 'showsTable', ['showName'], unique=False)
    op.create_table('crewAssignmentsTable',
    sa.Column('showID', sa.UUID(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('departmentID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departmentID'], ['departmentsTable.departmentID'], ),
    sa.ForeignKeyConstraint(['showID'], ['showsTable.showID'], ),
    sa.ForeignKeyConstraint(['userID'], ['userTable.ID'], ),
    sa.PrimaryKeyConstraint('userID', 'departmentID')
    )
    op.create_table('guestAccessLinksTable',
    sa.Column('linkID', sa.Integer(), nullable=False),
    sa.Column('accessToken', sa.String(), nullable=False),
    sa.Column('showID', sa.UUID(), nullable=True),
    sa.Column('departmentID', sa.Integer(), nullable=False),
    sa.Column('linkName', sa.String(), nullable=True),
    sa.Column('expiresAt', sa.DateTime(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['departmentID'], ['departmentsTable.departmentID'], ),
    sa.ForeignKeyConstraint(['showID'], ['showsTable.showID'], ),
    sa.PrimaryKeyConstraint('linkID')
    )
    op.create_index(op.f('ix_guestAccessLinksTable_accessToken'), 'guestAccessLinksTable', ['accessToken'], unique=True)
    op.create_index(op.f('ix_guestAccessLinksTable_linkID'), 'guestAccessLinksTable', ['linkID'], unique=False)
    op.create_table('scriptsTable',
    sa.Column('scriptID', sa.Integer(), nullable=False),
    sa.Column('scriptName', sa.String(), nullable=True),
    sa.Column('scriptStatus', sa.String(), nullable=True),
    sa.Column('showID', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['showID'], ['showsTable.showID'], ),
    sa.PrimaryKeyConstraint('scriptID')
    )
    op.create_index(op.f('ix_scriptsTable_scriptID'), 'scriptsTable', ['scriptID'], unique=False)
    op.create_table('scriptElementsTable',
    sa.Column('elementID', sa.Integer(), nullable=False),
    sa.Column('scriptID', sa.Integer(), nullable=True),
    sa.Column('departmentID', sa.Integer(), nullable=True),
    sa.Column('elementType', sa.String(), nullable=True),
    sa.Column('elementOrder', sa.Integer(), nullable=False),
    sa.Column('cueNumber', sa.String(), nullable=True),
    sa.Column('elementDescription', sa.Text(), nullable=True),
    sa.Column('elementTime', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['departmentID'], ['departmentsTable.departmentID'], ),
    sa.ForeignKeyConstraint(['scriptID'], ['scriptsTable.scriptID'], ),
    sa.PrimaryKeyConstraint('elementID')
    )
    op.create_index(op.f('ix_scriptElementsTable_elementID'), 'scriptElementsTable', ['elementID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scriptElementsTable_elementID'), table_name='scriptElementsTable')
    op.drop_table('scriptElementsTable')
    op.drop_index(op.f('ix_scriptsTable_scriptID'), table_name='scriptsTable')
    op.drop_table('scriptsTable')
    op.drop_index(op.f('ix_guestAccessLinksTable_linkID'), table_name='guestAccessLinksTable')
    op.drop_index(op.f('ix_guestAccessLinksTable_accessToken'), table_name='guestAccessLinksTable')
    op.drop_table('guestAccessLinksTable')
    op.drop_table('crewAssignmentsTable')
    op.drop_index(op.f('ix_showsTable_showName'), table_name='showsTable')
    op.drop_table('showsTable')
    op.drop_index(op.f('ix_userTable_userName'), table_name='userTable')
    op.drop_index(op.f('ix_userTable_emailAddress'), table_name='userTable')
    op.drop_index(op.f('ix_userTable_clerk_user_id'), table_name='userTable')
    op.drop_index(op.f('ix_userTable_ID'), table_name='userTable')
    op.drop_table('userTable')
    op.drop_index(op.f('ix_departmentsTable_departmentID'), table_name='departmentsTable')
    op.drop_table('departmentsTable')
    # ### end Alembic commands ###
