"""Create initial database schema

Revision ID: c640b091f5ab
Revises: 
Create Date: 2025-07-01 11:10:07.562097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c640b091f5ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userTable',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('userName', sa.String(), nullable=True),
    sa.Column('emailAddress', sa.String(), nullable=True),
    sa.Column('fullnameFirst', sa.String(), nullable=True),
    sa.Column('fullnameLast', sa.String(), nullable=True),
    sa.Column('profileImgURL', sa.String(), nullable=True),
    sa.Column('userRole', sa.String(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dateUpdated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_userTable_ID'), 'userTable', ['ID'], unique=False)
    op.create_index(op.f('ix_userTable_clerk_user_id'), 'userTable', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_userTable_emailAddress'), 'userTable', ['emailAddress'], unique=True)
    op.create_index(op.f('ix_userTable_userName'), 'userTable', ['userName'], unique=True)
    op.create_table('showsTable',
    sa.Column('showID', sa.Integer(), nullable=False),
    sa.Column('showName', sa.String(), nullable=False),
    sa.Column('showVenue', sa.String(), nullable=True),
    sa.Column('showDate', sa.Date(), nullable=True),
    sa.Column('ownerID', sa.Integer(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dateUpdated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ownerID'], ['userTable.ID'], ),
    sa.PrimaryKeyConstraint('showID')
    )
    op.create_index(op.f('ix_showsTable_showID'), 'showsTable', ['showID'], unique=False)
    op.create_index(op.f('ix_showsTable_showName'), 'showsTable', ['showName'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_showsTable_showName'), table_name='showsTable')
    op.drop_index(op.f('ix_showsTable_showID'), table_name='showsTable')
    op.drop_table('showsTable')
    op.drop_index(op.f('ix_userTable_userName'), table_name='userTable')
    op.drop_index(op.f('ix_userTable_emailAddress'), table_name='userTable')
    op.drop_index(op.f('ix_userTable_clerk_user_id'), table_name='userTable')
    op.drop_index(op.f('ix_userTable_ID'), table_name='userTable')
    op.drop_table('userTable')
    # ### end Alembic commands ###
